<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use App\Game;

class CreateFixTable extends Migration {

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        \DB::table('coin')->truncate();
        \DB::table('deposits')->truncate();
        \DB::table('dice')->truncate();
        \DB::table('double_admin')->truncate();
        \DB::table('double_bets')->truncate();
        \DB::table('double_games')->truncate();
        \DB::table('perevod')->truncate();
        \DB::table('shop_offers')->truncate();
        
        \DB::table('cens')->insert([
            ['text' => 'csgo.ru' , 'repl' => '***'],
            ['text' => 'csgo777.ru' , 'repl' => '***'],
            ['text' => 'csgobomw.ru' , 'repl' => '***'],
            ['text' => 'csgoup.ru' , 'repl' => '***'],
            ['text' => 'csgoezmoney.com' , 'repl' => '***'],
            ['text' => 'csgohide.ru' , 'repl' => '***'],
            ['text' => 'evacsgo.ru' , 'repl' => '***'],
            ['text' => 'eggcsgo.ru' , 'repl' => '***'],
            ['text' => 'csgofire.com' , 'repl' => '***'],
            ['text' => 'csgobet.ru' , 'repl' => '***'],
            ['text' => 'csgetto.com' , 'repl' => '***'],
            ['text' => 'csgohappy.com' , 'repl' => '***'],
            ['text' => 'csgoin.ru' , 'repl' => '***'],
            ['text' => 'csgooffline.com' , 'repl' => '***'],
            ['text' => 'csgobich.com' , 'repl' => '***'],
            ['text' => 'csgo.porn' , 'repl' => '***'],
            ['text' => 'csgomassive.com' , 'repl' => '***'],
            ['text' => 'lootbank.ru' , 'repl' => '***'],
            ['text' => 'csgo.pink' , 'repl' => '***'],
            ['text' => 'csfate.com' , 'repl' => '***'],
            ['text' => 'csgont.com' , 'repl' => '***'],
            ['text' => 'csgolime.com' , 'repl' => '***'],
            ['text' => 'csgo-x.ru' , 'repl' => '***'],
            ['text' => 'csgofade.net' , 'repl' => '***'],
            ['text' => 'exgame.pro' , 'repl' => '***'],
            ['text' => 'csgorides.com' , 'repl' => '***'],
            ['text' => 'csfox.ru' , 'repl' => '***'],
            ['text' => 'kickback.com' , 'repl' => '***'],
            ['text' => 'csgoshik.ru' , 'repl' => '***'],
            ['text' => 'csgogold.ru' , 'repl' => '***'],
            ['text' => 'joyskins.top' , 'repl' => '***'],
            ['text' => 'dragonskins.ru' , 'repl' => '***'],
            ['text' => 'csgorate.net' , 'repl' => '***'],
            ['text' => 'kingskin.org' , 'repl' => '***'],
            ['text' => 'csgowd.ru' , 'repl' => '***'],
            ['text' => 'csgo.in' , 'repl' => '***'],
            ['text' => 'csgo-rich.ru' , 'repl' => '***'],
            ['text' => 'drop777.com' , 'repl' => '***'],
            ['text' => 'challengeskins.com' , 'repl' => '***'],
            ['text' => 'easyknifs.ru' , 'repl' => '***'],
            ['text' => 'csgohandouts.com' , 'repl' => '***'],
            ['text' => 'csgo-bro.xyz' , 'repl' => '***'],
            ['text' => 'csgo-x.pro' , 'repl' => '***'],
            ['text' => 'cases2x.com' , 'repl' => '***'],
            ['text' => 'csammo.ru' , 'repl' => '***'],
            ['text' => 'csgonice.com' , 'repl' => '***'],
            ['text' => 'csgobird.com' , 'repl' => '***'],
            ['text' => 'csgodep.com' , 'repl' => '***'],
            ['text' => 'csgo-cash.com' , 'repl' => '***'],
            ['text' => 'highskinz.com' , 'repl' => '***'],
            ['text' => 'csgospeed.com' , 'repl' => '***'],
            ['text' => 'pvpro.com' , 'repl' => '***'],
            ['text' => 'csgoup.com' , 'repl' => '***'],
            ['text' => 'csgoteamroll.com' , 'repl' => '***'],
            ['text' => 'skinrekt.com' , 'repl' => '***'],
            ['text' => 'dota2bomj.com' , 'repl' => '***'],
            ['text' => 'dotamix.com' , 'repl' => '***'],
            ['text' => 'csgox14.com' , 'repl' => '***'],
            ['text' => 'pray4luck.com' , 'repl' => '***'],
            ['text' => 'csgotune.com' , 'repl' => '***'],
            ['text' => 'm9snik.com' , 'repl' => '***'],
            ['text' => 'csgo2x.com' , 'repl' => '***'],
            ['text' => 'csgo-fox.com' , 'repl' => '***'],
            ['text' => 'csgojoe.com' , 'repl' => '***'],
            ['text' => 'csgopolygon.com' , 'repl' => '***'],
            ['text' => 'csgoarena.com' , 'repl' => '***'],
            ['text' => 'win-fast.ru' , 'repl' => '***'],
            ['text' => 'skinbowl.com' , 'repl' => '***'],
            ['text' => 'csgopoints.com' , 'repl' => '***'],
            ['text' => 'csgo4you.com' , 'repl' => '***'],
            ['text' => 'csgo777.com' , 'repl' => '***'],
            ['text' => 'csgo-happy.ru' , 'repl' => '***'],
            ['text' => 'ggwpdota.ru' , 'repl' => '***'],
            ['text' => 'csgonow.ru' , 'repl' => '***'],
            ['text' => 'csgopie.ru' , 'repl' => '***'],
            ['text' => 'csbets.ru' , 'repl' => '***'],
            ['text' => 'skins-pro.ru' , 'repl' => '***'],
            ['text' => 'csgolite.ru' , 'repl' => '***'],
            ['text' => 'csgohap.ru' , 'repl' => '***'],
            ['text' => 'bichruletka.ru' , 'repl' => '***'],
            ['text' => 'csgoluxe.ru' , 'repl' => '***'],
            ['text' => 'asedrop.ru' , 'repl' => '***'],
            ['text' => 'cs-azart.ru' , 'repl' => '***'],
            ['text' => 'csgomeat.ru' , 'repl' => '***'],
            ['text' => 'csgobomj.ru' , 'repl' => '***'],
            ['text' => 'cs-box.ru' , 'repl' => '***'],
            ['text' => 'doublehf.ru' , 'repl' => '***'],
            ['text' => 'csgo-gg-wp.ru' , 'repl' => '***'],
            ['text' => 'csgohf.ru' , 'repl' => '***'],
            ['text' => 'стим' , 'repl' => 'steam'],
            ['text' => 'skinsgo.com' , 'repl' => '***'],
            ['text' => 'csgofast.com' , 'repl' => '***'],
            ['text' => 'bich.com' , 'repl' => '***'],
            ['text' => 'g2a.com' , 'repl' => '***'],
            ['text' => 'elite-bets.' , 'repl' => '***'],
            ['text' => 'csgostep.com' , 'repl' => '***'],
            ['text' => 'csgo-bolt.ru' , 'repl' => '***'],
            ['text' => 'bets.gg' , 'repl' => '***'],
            ['text' => 'csgorullete' , 'repl' => '***'],
            ['text' => 'upskins.com' , 'repl' => '***'],
            ['text' => 'bro-csgo.pro' , 'repl' => '***'],
            ['text' => 'swap.csgo.com' , 'repl' => '***'],
            ['text' => 'csgoloto.com' , 'repl' => '***'],
            ['text' => 'silicon-power.com' , 'repl' => '***'],
            ['text' => 'csgowest.com' , 'repl' => '***'],
            ['text' => 'skinbets.com' , 'repl' => '***'],
            ['text' => 'csgohype.com' , 'repl' => '***'],
            ['text' => 'csgoduck.com' , 'repl' => '***'],
            ['text' => 'csgofinish.com' , 'repl' => '***'],
            ['text' => 'csgosell.com' , 'repl' => '***'],
            ['text' => 'csgobetroulette.com' , 'repl' => '***'],
            ['text' => 'oneleday.com' , 'repl' => '***'],
            ['text' => 'good-gabe.net' , 'repl' => '***'],
            ['text' => 'imbahase.com' , 'repl' => '***'],
            ['text' => 'csgohot.com' , 'repl' => '***'],
            ['text' => 'csgofunpot.com' , 'repl' => '***'],
            ['text' => 'csgoreaper.com' , 'repl' => '***'],
            ['text' => 'winitem.com' , 'repl' => '***'],
            ['text' => 'csgofasted.ru' , 'repl' => '***'],
            ['text' => 'csgotrophy.ru' , 'repl' => '***'],
            ['text' => 'cstitan.ru' , 'repl' => '***'],
            ['text' => 'csgoigra.ru' , 'repl' => '***'],
            ['text' => 'csgogood.ru' , 'repl' => '***'],
            ['text' => 'csgoselector.ru' , 'repl' => '***'],
            ['text' => 'factorynew.ru' , 'repl' => '***'],
            ['text' => 'csgohappy.ru' , 'repl' => '***'],
            ['text' => 'd2d-roulette.ru' , 'repl' => '***'],
            ['text' => 'ruletka-cs-go.ru' , 'repl' => '***'],
            ['text' => 'csgospy.ru' , 'repl' => '***'],
            ['text' => 'csgonoj.ru' , 'repl' => '***'],
            ['text' => 'csgobich.ru' , 'repl' => '***'],
            ['text' => 'csgobomj' , 'repl' => '***'],
            ['text' => 'fungun.net' , 'repl' => '***'],
            ['text' => 'csgohouse.org' , 'repl' => '***'],
            ['text' => 'cslots.ru' , 'repl' => '***'],
            ['text' => 'cspolygon.com' , 'repl' => '***'],
            ['text' => 'cspolygon' , 'repl' => '***'],
            ['text' => 'polygon' , 'repl' => '***'],
            ['text' => 'skinswinner.ru' , 'repl' => '***'],
            ['text' => 'skinswinner' , 'repl' => '***'],
            ['text' => 'csduo.su' , 'repl' => '***'],
            ['text' => 'csgobay.ru' , 'repl' => '***'],
            ['text' => 'cs-upskins.ru' , 'repl' => '***'],
            ['text' => 'cs.money' , 'repl' => '***'],
            ['text' => 'csgo-up.ru' , 'repl' => '***'],
            ['text' => 'cs-arms.ru' , 'repl' => '***'],
            ['text' => 'forcedrop.ru' , 'repl' => '***'],
            ['text' => '777hp.ru' , 'repl' => '***'],
            ['text' => 'csbahis.com' , 'repl' => '***'],
            ['text' => 'csgo.life ' , 'repl' => '***'],
            ['text' => 'csgo-farming.ru ' , 'repl' => '***'],
            ['text' => 'csgoempire.com' , 'repl' => '***'],
            ['text' => 'csgo-win.pro' , 'repl' => '***'],
            ['text' => 'csgotitan.net' , 'repl' => '***'],
            ['text' => 'csgobomb.com' , 'repl' => '***'],
            ['text' => 'csgoenjoy.com' , 'repl' => '***'],
            ['text' => 'csgomoon.ru' , 'repl' => '***'],
            ['text' => 'csgovegas.ru' , 'repl' => '***'],
            ['text' => 'battlego.net' , 'repl' => '***'],
            ['text' => 'rollcsgo.ru' , 'repl' => '***'],
            ['text' => 'back.com' , 'repl' => '***'],
            ['text' => 'filldrop.ru' , 'repl' => '***'],
            ['text' => 'csgoatse.com' , 'repl' => '***'],
            ['text' => 'cases2.com' , 'repl' => '***'],
            ['text' => 'csgotape.ru' , 'repl' => '***'],
            ['text' => 'csgodouble.gg' , 'repl' => '***'],
            ['text' => 'csgocasino.net' , 'repl' => '***'],
            ['text' => 'csgow.ru' , 'repl' => '***'],
            ['text' => 'csgood.net' , 'repl' => '***'],
            ['text' => 'skinwin.club' , 'repl' => '***'],
            ['text' => 'csgotrinity.com' , 'repl' => '***'],
            ['text' => 'twitch.tv/shurzg' , 'repl' => '***'],
            ['text' => 'skingames.co' , 'repl' => '***'],
            ['text' => 'csgo-bomb.com' , 'repl' => '***'],
            ['text' => 'csgoseller.ru' , 'repl' => '***'],
            ['text' => 'csgofind.com' , 'repl' => '***'],
            ['text' => 'cslottery.su' , 'repl' => '***'],
            ['text' => 'csmale.ru' , 'repl' => '***'],
            ['text' => 'csgofeeling.ru' , 'repl' => '***'],
            ['text' => 'csgo-vulcan.ru' , 'repl' => '***'],
            ['text' => 'elitedrop.ru' , 'repl' => '***'],
            ['text' => 'csgoburn.com' , 'repl' => '***'],
            ['text' => '4csgo.net' , 'repl' => '***'],
            ['text' => 'csgoldpot.com' , 'repl' => '***'],
            ['text' => 'overdrop.ru' , 'repl' => '***'],
            ['text' => 'csgostars.ru' , 'repl' => '***'],
            ['text' => 'csgo-fate.ru' , 'repl' => '***'],
            ['text' => 'd2selector.ru' , 'repl' => '***'],
            ['text' => 'csgo-tech.ru' , 'repl' => '***'],
            ['text' => 'magicdrop.ru' , 'repl' => '***'],
            ['text' => 'tydy.ru' , 'repl' => '***'],
            ['text' => 'timeloot.ru' , 'repl' => '***'],
            ['text' => 'cases2x.ru' , 'repl' => '***'],
            ['text' => 'ensw.ru' , 'repl' => '***'],
            ['text' => 'csgofocus.ru' , 'repl' => '***'],
            ['text' => 'botcatlottery.ru' , 'repl' => '***'],
            ['text' => 'csgohax.ru' , 'repl' => '***'],
            ['text' => 'csgodep.ru' , 'repl' => '***'],
            ['text' => 'ytmonster.ru' , 'repl' => '***'],
            ['text' => 'csroller.ru' , 'repl' => '***'],
            ['text' => 'wayshot.com' , 'repl' => '***'],
            ['text' => 'godbets.com' , 'repl' => '***'],
            ['text' => 'csgofap.com' , 'repl' => '***'],
            ['text' => 'gamdom.com' , 'repl' => '***'],
            ['text' => 'cs go.com' , 'repl' => '***'],
            ['text' => 'pvp.pro.com' , 'repl' => '***'],
            ['text' => 'csgoninja.com' , 'repl' => '***'],
            ['text' => 'csgoezy.com' , 'repl' => '***'],
            ['text' => 'skinsez.com' , 'repl' => '***'],
            ['text' => 'fairbone.com' , 'repl' => '***'],
            ['text' => 'lite-bet.com' , 'repl' => '***'],
            ['text' => 'csgoroll.com' , 'repl' => '***'],
            ['text' => 'csgowitch.com' , 'repl' => '***'],
            ['text' => 'csgomix.com' , 'repl' => '***'],
            ['text' => 'sknsgo.com' , 'repl' => '***'],
            ['text' => '***.com' , 'repl' => '***'],
            ['text' => 'csgo7.com' , 'repl' => '***'],
            ['text' => 'dota2house.com' , 'repl' => '***'],
            ['text' => 'ensistudio.com' , 'repl' => '***'],
            ['text' => 'csgodpeed.com' , 'repl' => '***'],
            ['text' => 'csgo-go.com' , 'repl' => '***'],
            ['text' => 'hyperdraft.com' , 'repl' => '***'],
            ['text' => 'skinduplex.com' , 'repl' => '***'],
            ['text' => 'uxplosive.com' , 'repl' => '***'],
            ['text' => 'fastwits.com' , 'repl' => '***'],
            ['text' => 'csgocookie.com' , 'repl' => '***'],
            ['text' => '*** .com' , 'repl' => '***'],
            ['text' => 'dropmoney.net' , 'repl' => '***'],
            ['text' => 'skinmine.net' , 'repl' => '***'],
            ['text' => 'ecyberbet.com' , 'repl' => '***'],
            ['text' => 'csbets.su' , 'repl' => '***'],
            ['text' => 'csgodoubly.com' , 'repl' => '***'],
            ['text' => 'elitecase.net' , 'repl' => '***'],
            ['text' => 'csgo-vegas.net' , 'repl' => '***'],
            ['text' => 'csgorulles.ru' , 'repl' => '***'],
            ['text' => 'kickback.co' , 'repl' => '***'],
            ['text' => 'flashskins.net' , 'repl' => '***'],
            ['text' => 'easydrop.ru' , 'repl' => '***'],
            ['text' => 'skinwin.com' , 'repl' => '***'],
            ['text' => 'csgoboss' , 'repl' => '***'],
            ['text' => 'csray.ru' , 'repl' => '***'],
            ['text' => 'csgoelitup.ru' , 'repl' => '***'],
            ['text' => 'skinup.gg' , 'repl' => '***'],
            ['text' => 'csgogrim.net' , 'repl' => '***'],
            ['text' => 'csgolottery.pro' , 'repl' => '***'],
            ['text' => 'games-lottery.com' , 'repl' => '***'],
            ['text' => 'csgolabz.com' , 'repl' => '***'],
            ['text' => 'vkcsgo.com' , 'repl' => '***'],
            ['text' => 'csgowd.net' , 'repl' => '***'],
            ['text' => 'easy.gl' , 'repl' => '***'],
            ['text' => 'csgobig.com' , 'repl' => '***'],
            ['text' => 'cs-bro.pro' , 'repl' => '***'],
            ['text' => 'csgoboobs.ru' , 'repl' => '***'],
            ['text' => 'wager.gg' , 'repl' => '***'],
            ['text' => 'csgowhale.com' , 'repl' => '***'],
            ['text' => 'justcase.net' , 'repl' => '***'],
            ['text' => 'ezyup.ru' , 'repl' => '***'],
            ['text' => 'givemeskins.com' , 'repl' => '***'],
            ['text' => 'skinsmash.com' , 'repl' => '***'],
            ['text' => 'csgotitannet' , 'repl' => '***'],
            ['text' => 'windrop.ru' , 'repl' => '***'],
            ['text' => 'csgomax.net' , 'repl' => '***'],
            ['text' => 'gabe-up.ru' , 'repl' => '***'],
            ['text' => 'elitcase.net' , 'repl' => '***']
        ]);

    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('cens');
    }

}
